spring.application.name=glossapp

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

#spring.security.oauth2.resourceserver.jwt.issuer-uri=
#spring.security.oauth2.resourceserver.jwt.audiences=